config/routes.rb
Rails.application.routes.draw do
  get 'area_kansai/areakansai'

  get 'area_notice/area-notice'

  get 'search/new'

  get 'inquiry/new'

  get 'mid_nav/new'

  get 'service/new'

  get 'amenities/new'

  get 'spacetype/new'

  get 'capacities/new'

  get 'areas/new'

  get 'category/new'

  get 'eventtypes/new'

  get 'party/new'

  get 'commercialtransaction/new'

  get 'companyprofile/new'

  get 'comingsoon/new'

  get 'privacypolicy/new'

  get 'lodgingguests/new'

  get 'lodgingagreement/new'

  get 'guide/new'

  get 'flowsettlement/flowsettlement'

  get 'registration/registration'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,
  skip: [
    :session,
    :password,
    :registration,
    :confirmation
  ],
  controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  scope '(:locale)', locale: /en/ do

    # We define here a route inside the locale thats just saves the current locale in the session
    get 'omniauth/:provider' => 'users/omniauth#localized', as: :localized_omniauth
    devise_for :users,
    skip: :omniauth_callbacks,
    controllers: {
      sessions:            'users/sessions',
      registrations:       'users/registrations',
      passwords:           'users/passwords',
      confirmations:       'users/confirmations'
    }

    resources :profiles, only: [:show] do
      resources :profile_images, only: [:show]
    end

    resource :profile, except: [:index, :show] do
      collection do
        get 'return_listing' => 'profiles#return_listing'
      end
      resource :profile_image, except: [:index, :show] do
        collection do
          get 'return_listing' => 'profile_images#return_listing'
        end
      end
      resource :identification, except: [:edit, :update]
      resource :bank_account, except: [:edit, :update]
    end

  #  resources :auths

    get 'dashboard'                           => 'dashboard#index'
    get 'dashboard/host_reservation_manager'  => 'dashboard#host_reservation_manager'
    get 'dashboard/guest_reservation_manager' => 'dashboard#guest_reservation_manager'
    # get 'reviews'                             => 'profiles#review', as: 'user_review'
    # get 'introductions'                       => 'profiles#introduction', as: 'introduction'

    resources :message_threads, except: [:edit]

    resources :messages do
      collection do
        post 'send_message'
      end
    end

    resources :favorites, only: [:index, :destroy] do
      collection do
        post   '/:listing_id', action: 'create', as: "add"
      end
    end

    resources :listings do
      collection do
        get 'search',        action: 'search'
        get 'search_result', action: 'search_result'
        get 'page/:page',    action: 'index'
      end
      resources :listing_images, only: [:show, :create, :update, :destroy] do
        get 'manage', on: :collection
      end
      #resources :listing_videos do
      #  get 'manage', on: :collection
      #end
      resources :listing_ngevents do
        get 'manage', on: :collection
        get 'search', on: :collection
        post 'delete_all_day', on: :collection
      end
      resources :listing_okevents do
        get 'manage', on: :collection
        get 'search', on: :collection
        post 'delete_all_day', on: :collection
      end
      get 'publish',   action: 'publish',   as: 'publish'
      get 'unpublish', action: 'unpublish', as: 'unpublish'
    end

    resources :reservations, only: [:show, :create, :update] do
      resource :reviews do
        resource :review_replies
      end
    end

    #resources :wishlists

    resources :inquiries, only: [:new, :create] do
      collection do
        post :confirm
      end
    end

    if Rails.env.review_app?
      mount LetterOpenerWeb::Engine, at: '/letter_opener'
    end

    root 'welcome#index'

    get 'templates' => 'templates#invoice'
  end

end

app/models/listing_image.rb
class ListingImage < ActiveRecord::Base
  belongs_to :listing

  mount_uploader :image, DefaultImageUploader

  scope :slideshow_images, -> id { where(listing_id: id) }
  scope :order_asc, -> { order('order_num asc') }
  scope :cover_image, -> listing_id { where(listing_id: listing_id) }
  scope :records, -> listing_id { where(listing_id: listing_id) }
end

app/controllers/listing_images_controller.rb
class ListingImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_listing_image, only: [:update, :destroy]
  before_action :set_listing
  authorize_resource

  def manage
    authorize! :manage, @listing
    listing_images = ListingImage.records(params[:listing_id])
    @listing_images = listing_images
    @listing_image = ListingImage.new
  end

  def create
    @listing_image = ListingImage.new(listing_image_params)
    count = ListingImage.where(listing_id: @listing.id).size
    @listing_image.order_num = count
    if @listing_image.save
      redirect_to manage_listing_listing_images_path(@listing.id), notice: I18n.t('alerts.listing_images.save.success', model: ListingImage.model_name.human)
      #render json: { success: true, status: :created, location: @listing_image }
    else
      redirect_to manage_listing_listing_images_path(@listing.id), notice: I18n.t('alerts.listing_images.save.failure', model: ListingImage.model_name.human)
      #render json: { success: false, errors: @listing_image.errors, status: :unprocessable_entity }
    end
  end

  def update
    if @listing_image.update(listing_image_params)
      redirect_to manage_listing_listing_images_path(@listing.id), notice: I18n.t('alerts.listing_images.save.success', model: ListingImage.model_name.human)
      #render json: { success: true, status: :ok, location: @listing_image, notice: Settings.listing_images.save.success }
    else
      redirect_to manage_listing_listing_images_path(@listing.id), notice: I18n.t('alerts.listing_images.save.failure', model: ListingImage.model_name.human)
      #render json: { success: false, errors: @listing_image.errors, status: :unprocessable_entity, notice: Settings.listing_images.save.failure }
    end
  end

  def destroy
    @listing_image.destroy
    respond_to do |format|
      format.html { redirect_to manage_listing_listing_images_path(@listing_image.listing_id), notice: 'ListingImage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_listing_image
      @listing_image = ListingImage.find(params[:id])
    end

    def set_listing
      @listing = Listing.find(params[:listing_id])
    end

    def listing_image_params
      params.require(:listing_image).permit(:listing_id, :image, :caption)
        .merge(listing_id: @listing.id)
    end

end

app/views/listing_images/_form.html.slim
.row
  - @listing_images.each do |image|
    .col-lg-4.col-md-4.listing-image-wrapper.matchHeight
      = simple_form_for([@listing, image], html: {class: "form--sp"} ) do |f|
        .panel.photo-item
          = image_tag(image.image.thumb)
          = link_to listing_listing_image_path(@listing, image), method: :delete, rel: "nofollow", class: 'btn-photo-delete', data: { confirm: "本当に削除しますか？" } do
            = image_tag 'icons/delete.png'
          .listing-image-caption-wrapper.panel-body.panel-condensed
            = f.input_field :caption, as: :text, placeholder: t('activerecord.placeholders.listing_image.caption')
          .text-center.row-space-2
            = f.button :submit, "更新", class: "btn-primary text-center", id: 'listing-manager-listing-image-submit'
  .col-lg-4.col-md-4
    .panel.photo-item.empty-photo-frame
      = simple_form_for([@listing, @listing_image], html: {class: "form--sp", multipart: true} ) do |f|
        = f.error_notification
        = f.hidden_field :listing_id, value: @listing.id
        .empty-photo-image
          = image_tag 'icons/photo.png'
        = f.label :image, "画像を追加する", class: 'text-center add-photo-link row-space-4 row-space-top-4'
        = f.file_field :image, as: :file, style: 'display:none;', data: { listing_id: @listing.id }, class: "file_input"

app/views/listing_images/manage.html.slim
- provide :title, t('.title', listing_image: ListingImage.model_name.human)
.manage-listings
  = render partial: 'shared/manage_listing_header', locals: { listing: @listing }
  .manage-listing-row-container
    .manage-listing-content.col-md-9.col-offset-3
      .row-space-top-4
        h3.text-center.row-space-2
          = t('.title', listing_image: ListingImage.model_name.human)
        p.text-center.row-space-6
          = t('.text_html', guest: t('name.guest'), listing: Listing.model_name.human, listing_image: ListingImage.model_name.human)
      = render 'form'

    = render partial: 'shared/manage_listing_nav'