config/routes.rb
Rails.application.routes.draw do
  get 'area_kansai/areakansai'

  get 'area_notice/area-notice'

  get 'search/new'

  get 'inquiry/new'

  get 'mid_nav/new'

  get 'service/new'

  get 'amenities/new'

  get 'spacetype/new'

  get 'capacities/new'

  get 'areas/new'

  get 'category/new'

  get 'eventtypes/new'

  get 'party/new'

  get 'commercialtransaction/new'

  get 'companyprofile/new'

  get 'comingsoon/new'

  get 'privacypolicy/new'

  get 'lodgingguests/new'

  get 'lodgingagreement/new'

  get 'guide/new'

  get 'flowsettlement/flowsettlement'

  get 'registration/registration'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,
  skip: [
    :session,
    :password,
    :registration,
    :confirmation
  ],
  controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  scope '(:locale)', locale: /en/ do

    # We define here a route inside the locale thats just saves the current locale in the session
    get 'omniauth/:provider' => 'users/omniauth#localized', as: :localized_omniauth
    devise_for :users,
    skip: :omniauth_callbacks,
    controllers: {
      sessions:            'users/sessions',
      registrations:       'users/registrations',
      passwords:           'users/passwords',
      confirmations:       'users/confirmations'
    }

    resources :profiles, only: [:show] do
      resources :profile_images, only: [:show]
    end

    resource :profile, except: [:index, :show] do
      collection do
        get 'return_listing' => 'profiles#return_listing'
      end
      resource :profile_image, except: [:index, :show] do
        collection do
          get 'return_listing' => 'profile_images#return_listing'
        end
      end
      resource :identification, except: [:edit, :update]
      resource :bank_account, except: [:edit, :update]
    end

  #  resources :auths

    get 'dashboard'                           => 'dashboard#index'
    get 'dashboard/host_reservation_manager'  => 'dashboard#host_reservation_manager'
    get 'dashboard/guest_reservation_manager' => 'dashboard#guest_reservation_manager'
    # get 'reviews'                             => 'profiles#review', as: 'user_review'
    # get 'introductions'                       => 'profiles#introduction', as: 'introduction'

    resources :message_threads, except: [:edit]

    resources :messages do
      collection do
        post 'send_message'
      end
    end

    resources :favorites, only: [:index, :destroy] do
      collection do
        post   '/:listing_id', action: 'create', as: "add"
      end
    end

    resources :listings do
      collection do
        get 'search',        action: 'search'
        get 'search_result', action: 'search_result'
        get 'page/:page',    action: 'index'
      end
      resources :listing_images, only: [:show, :create, :update, :destroy] do
        get 'manage', on: :collection
      end
      #resources :listing_videos do
      #  get 'manage', on: :collection
      #end
      resources :listing_ngevents do
        get 'manage', on: :collection
        get 'search', on: :collection
        post 'delete_all_day', on: :collection
      end
      resources :listing_okevents do
        get 'manage', on: :collection
        get 'search', on: :collection
        post 'delete_all_day', on: :collection
      end
      get 'publish',   action: 'publish',   as: 'publish'
      get 'unpublish', action: 'unpublish', as: 'unpublish'
    end

    resources :reservations, only: [:show, :create, :update] do
      resource :reviews do
        resource :review_replies
      end
    end

    #resources :wishlists

    resources :inquiries, only: [:new, :create] do
      collection do
        post :confirm
      end
    end

    if Rails.env.review_app?
      mount LetterOpenerWeb::Engine, at: '/letter_opener'
    end

    root 'welcome#index'

    get 'templates' => 'templates#invoice'
  end

end

app/models/identification.rb
class Identification < ActiveRecord::Base
  belongs_to :profile
  belongs_to :processed_by, class_name: 'AdminUser'
  belongs_to :identification_type

  delegate :user, to: :profile

  enum status: %w(not_yet approved rejected)

  mount_uploader :image1, DefaultImageUploader
  mount_uploader :image2, DefaultImageUploader
  mount_uploader :image3, DefaultImageUploader

  validates :profile_id, presence: true
  validates :image1, presence: true
end

app/models/identification_type.rb
class IdentificationType < ActiveRecord::Base
  has_many :identifications

  validates :name, presence: true
  validates :name, uniqueness: true

  scope :availables, -> { where available: true }
end

app/controllers/identifications_controller.rb
class IdentificationsController < ApplicationController
  before_action :authenticate_user!

  def show
    return redirect_to action: :new unless current_user.identification
    @identification = current_user.profile.identification
  end

  def new
    return redirect_to action: :show if current_user.identification
    @identification = current_user.profile.build_identification
  end

  def create
    @identification = current_user.profile.build_identification(
      identification_params
    )

    respond_to do |format|
      if @identification.save
        flash[:notice] = I18n.t("alerts.identification.save.success",
                                model: Identification.model_name.human)
        format.html { redirect_to action: :show }
        format.json { head :created, location: profile_identification_path  }
      else
        flash[:alert] = I18n.t("alerts.identification.save.failure",
                                model: Identification.model_name.human)
        format.html { render :new, notice: @identification.errors.full_messages.join("<br>") }
        format.json { render json: @identification.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @identification = current_user.profile.identification
    @identification.destroy
    flash[:notice] = I18n.t("alerts.identification.delete.success",
                            model: Identification.model_name.human)
    redirect_to action: :new
  end

  private
  def identification_params
    params.require(:identification).permit(
      :image1,
      :image2,
      :image3,
      :note,
    )
  end
end

app/views/identifications/_form.html.slim
= simple_form_for(identification, url: profile_identification_url,
  as: :identification, html: { class: "form--sp" }) do |f|
  = f.error_notification

  .card.row-space-4
    .card-header
      = t('views.identifications.form.header')
    .card-body
      .row.row-condensed.row-space-4
        label.text-right.col-3
          = t('views.identifications.form.available_types')
        .col-8
          ul
            - IdentificationType.availables.each do |id_type|
              li = id_type.name

      - if current_user.identification.new_record?
        .row.row-condensed.row-space-4
          label.text-right.col-3
            = t('views.identifications.form.images')
          .col-8
            ul.list-unstyled.identification-attachments
              li
                = f.file_field :image1, class: "row-space-top-1-file"
            = link_to "[+] #{t('views.identifications.form.add_files')}",
              'javascript:void(0)', class: 'add-identification-attachment'

      - else
        .row.row-condensed.row-space-4
          .text-right.col-3
            = t('views.identifications.form.status')
          .col-8
            - if current_user.identification_approved?
              = t('views.identifications.form.approved')
            - else
              = t('views.identifications.form.processing')

        .row.row-condensed.row-space-4
          label.text-right.col-3
            = Identification.human_attribute_name :image1
          = image_tag(identification.image1.url, width: '320px')

          - if identification.image2.present?
            .row.row-condensed.row-space-4
              label.text-right.col-3
                = Identification.human_attribute_name :image2
              = image_tag(identification.image2.url, width: '320px')
          - if identification.image3.present?
            .row.row-condensed.row-space-4
              label.text-right.col-3
                = Identification.human_attribute_name :image3
              = image_tag(identification.image3.url, width: '320px')

        .row.row-condensed.row-space-4
          label.text-right.col-3
            = t('views.identifications.form.update')
          .col-8
            ul.list-unstyled.identification-attachments
              li
                = f.file_field :image1, class: "row-space-top-1-file"
            = link_to "[+] #{t('views.identifications.form.add_files')}",
              'javascript:void(0)', class: 'add-identification-attachment'

      .row.row-condensed.row-space-4
        label.text-right.col-3
          = Identification.human_attribute_name :note
        .col-8
          = f.input_field :note

  = f.button :submit, t('views.identifications.form.submit'), class: "btn btn-primary btn-large row-space-4"

app/views/identifications/new.html.slim
= render partial: 'shared/subnav'

.page-container.row-space-top-4.row-space-8
  .row
    .col-lg-3
      = render partial: 'shared/profile_sidenav'
    .col-lg-9
      = render 'form', profile: @identification.profile, identification: @identification

app/views/identifications/show.html.slim
= render partial: 'shared/subnav'

.page-container.row-space-top-4.row-space-8
  .row
    .col-lg-3
      = render partial: 'shared/profile_sidenav'
    .col-lg-9
      .card.row-space-4
        .card-header
          = t('views.identifications.form.header')
        .card-body
          .row.row-condensed.row-space-4
            .text-right.col-3
              = t('views.identifications.form.status')
            .col-8
              - if current_user.identification_approved?
                = t('views.identifications.form.approved')
              - else
                = t('views.identifications.form.processing')

          .row.row-condensed.row-space-4
            label.text-right.col-3
              = Identification.human_attribute_name :image1
            = image_tag(@identification.image1.url, width: '320px')

            - if @identification.image2.present?
              .row.row-condensed.row-space-4
                label.text-right.col-3
                  = Identification.human_attribute_name :image2
                = image_tag(@identification.image2.url, width: '320px')
            - if @identification.image3.present?
              .row.row-condensed.row-space-4
                label.text-right.col-3
                  = Identification.human_attribute_name :image3
                = image_tag(@identification.image3.url, width: '320px')

          .row.row-condensed.row-space-4
            .col-8.col-offset-3
              label = t('views.identifications.form.update_msg')
              = link_to t('views.identifications.form.delete'), profile_identification_path,
                class: 'btn btn-danger pull-right', method: :delete, title: @identification,
                data: { confirm: t('views.identifications.form.confirm') }